// sim_intrinsics_test.ls — the intrinsic front-end (SDM-derived).
//
// The sim can now be fed a C-intrinsic kernel instead of assembly: each `_mm*` call is
// resolved to its mnemonic via the SDM-extracted intrinsic table (sim.intel.intrinsics,
// generated by tools/gen_intrinsics_from_sdm.py), lowered to Intel syntax, then run
// through the SAME pipeline (decode -> ports -> engine -> render). This is the new
// "visualise by intrinsic name" capability the SDM unlocks (XED has no intrinsic map).

import sim.intel.intrinsics as intr
import sim.intel.decode as decode
import sim.render as render
import std.core.vec
import std.core.str

def check(bool cond, Str name) -> bool {
    if cond { @print(f"  ok: {name}") }
    else { @print(f"  FAIL: {name}") }
    return cond
}

def main() {
    bool all = true

    // ---- the generated intrinsic -> mnemonic table ----
    Vec(intr.IntrinRow) tbl = intr.build_intrinsic_table()
    @print(f"=== SDM intrinsic table: {tbl.len()} intrinsics -> modelled mnemonic ===")
    all = check(tbl.len() >= 3000, "table covers 3000+ intrinsics") && all

    // ---- spot-check resolution (incl. width-sensitive group disambiguation) ----
    Str i1 = "_mm512_shuffle_epi8"
    all = check(intr.mnemonic_of(&tbl, &i1).eq?("vpshufb"), "shuffle_epi8 -> vpshufb") && all
    Str i2 = "_mm512_permutexvar_epi8"
    all = check(intr.mnemonic_of(&tbl, &i2).eq?("vpermb"), "permutexvar_epi8 -> vpermb") && all
    Str i3 = "_mm512_dpbusd_epi32"
    all = check(intr.mnemonic_of(&tbl, &i3).eq?("vpdpbusd"), "dpbusd_epi32 -> vpdpbusd") && all
    Str i4 = "_mm512_add_epi32"
    all = check(intr.mnemonic_of(&tbl, &i4).eq?("vpaddd"), "add_epi32 -> vpaddd (width-aware, not vpaddb)") && all
    Str i5 = "_mm512_add_epi8"
    all = check(intr.mnemonic_of(&tbl, &i5).eq?("vpaddb"), "add_epi8 -> vpaddb") && all
    Str i6 = "_mm512_cvtepi16_epi8"
    all = check(intr.mnemonic_of(&tbl, &i6).eq?("vpmovwb"), "cvtepi16_epi8 -> vpmovwb") && all
    Str i7 = "_mm_not_a_real_intrinsic"
    all = check(intr.mnemonic_of(&tbl, &i7).len() == 0, "unknown intrinsic -> \"\" (graceful)") && all

    // ---- lower a full intrinsic kernel to assembly ----
    Str src = ""
    src = f"{src}__m512i p = _mm512_permutexvar_epi8(idx, data)\n"
    src = f"{src}__m512i s = _mm512_shuffle_epi8(p, ctrl)\n"
    src = f"{src}__m512i d = _mm512_sllv_epi16(s, amt)\n"
    src = f"{src}acc = _mm512_dpbusd_epi32(acc, d, w)\n"
    src = f"{src}__m256i pk = _mm512_cvtepi16_epi8(acc)\n"

    Str asm = decode.lower_intrinsics(&src)
    @print("")
    @print("--- lowered assembly ---")
    @print(asm)

    Str m_permb = "vpermb p, idx, data"
    all = check(asm.contains?(&m_permb), "permutexvar lowered with ctrl=src0 (vpermb p, idx, data)") && all
    Str m_shuf = "vpshufb s, p, ctrl"
    all = check(asm.contains?(&m_shuf), "shuffle lowered (vpshufb s, p, ctrl)") && all
    Str m_dp = "vpdpbusd acc, acc, d, w"
    all = check(asm.contains?(&m_dp), "dpbusd lowered with accumulator (acc read+write)") && all
    Str m_pk = "vpmovwb pk, acc"
    all = check(asm.contains?(&m_pk), "down-convert lowered (vpmovwb pk, acc)") && all

    // ---- render the intrinsic kernel end-to-end (same analysis as asm) ----
    Str rep = render.render_intrinsics(src, render.MODE_TEXT())
    @print("")
    @print("--- render_intrinsics(text) ---")
    @print(rep)
    all = check(rep.len() > 0, "render produced output") && all
    Str needle = "vpdpbusd"
    all = check(rep.contains?(&needle), "report mentions a resolved mnemonic") && all

    if all { @print("SIM INTRINSICS PASS") }
    else { @print("SIM INTRINSICS FAIL") }
}
