/* doc_assets.c — built-in default CSS + HTML skeleton for `ls doc`.
 *
 * The default style mirrors docs/stdlib.html (flex sidebar + signature badges
 * + dark mode + responsive). These live here, not in main.c, so the large
 * string literals stay out of the CLI code. Both are overridable at runtime
 * via `ls doc --css <file>` and `ls doc --template <file>`.
 */
#include "doc_assets.h"

const char *const ls_doc_default_css =
    "  :root {\n"
    "    --bg: #fbfbfd; --fg: #1d1d22; --muted: #6b6b76; --line: #e4e4ea;\n"
    "    --accent: #6d28d9; --accent-soft: #f1ecfb; --code-bg: #f4f4f8;\n"
    "    --sig-bg: #faf8ff; --sig-border: #e7defb; --sidebar: #f6f6f9;\n"
    "    --tag-mut: #b91c1c; --tag-own: #047857; --tag-new: #1d4ed8;\n"
    "  }\n"
    "  @media (prefers-color-scheme: dark) {\n"
    "    :root {\n"
    "      --bg: #16161a; --fg: #e6e6ec; --muted: #9a9aa6; --line: #2a2a32;\n"
    "      --accent: #a78bfa; --accent-soft: #241b3a; --code-bg: #1e1e26;\n"
    "      --sig-bg: #1c1830; --sig-border: #352a52; --sidebar: #1a1a20;\n"
    "      --tag-mut: #f87171; --tag-own: #34d399; --tag-new: #60a5fa;\n"
    "    }\n"
    "  }\n"
    "  * { box-sizing: border-box; }\n"
    "  html { scroll-behavior: smooth; }\n"
    "  body {\n"
    "    margin: 0; background: var(--bg); color: var(--fg);\n"
    "    font: 15px/1.6 -apple-system, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif;\n"
    "  }\n"
    "  a { color: var(--accent); text-decoration: none; }\n"
    "  a:hover { text-decoration: underline; }\n"
    "  code, .sig { font-family: \"SF Mono\", \"Cascadia Code\", Consolas, \"Liberation Mono\", monospace; }\n"
    "  .wrap { display: flex; max-width: 1280px; margin: 0 auto; }\n"
    "  nav {\n"
    "    width: 250px; flex: 0 0 250px; background: var(--sidebar);\n"
    "    border-right: 1px solid var(--line); height: 100vh; position: sticky; top: 0;\n"
    "    overflow-y: auto; padding: 18px 14px 60px;\n"
    "  }\n"
    "  main { flex: 1 1 auto; min-width: 0; padding: 28px 38px 120px; }\n"
    "  .brand { font-weight: 700; font-size: 17px; margin: 4px 6px 14px; letter-spacing: -.2px; }\n"
    "  .brand small { display:block; font-weight: 400; font-size: 11.5px; color: var(--muted); margin-top:2px;}\n"
    "  nav .group { font-size: 11px; text-transform: uppercase; letter-spacing: .06em;\n"
    "    color: var(--muted); margin: 16px 6px 5px; font-weight: 700; }\n"
    "  nav a.item { display: block; padding: 4px 8px; border-radius: 6px; color: var(--fg);\n"
    "    font-size: 13.5px; }\n"
    "  nav a.item:hover { background: var(--accent-soft); text-decoration: none; }\n"
    "  h1 { font-size: 30px; letter-spacing: -.5px; margin: 0 0 6px; }\n"
    "  .lede { color: var(--muted); font-size: 16px; margin: 0 0 26px; max-width: 70ch; }\n"
    "  section { scroll-margin-top: 18px; padding-top: 10px; border-top: 1px solid var(--line);\n"
    "    margin-top: 34px; }\n"
    "  h2 { font-size: 23px; letter-spacing: -.3px; margin: 14px 0 4px; }\n"
    "  h2 .imp { font-size: 13px; font-weight: 500; color: var(--muted); margin-left: 10px;\n"
    "    font-family: monospace; }\n"
    "  h3 { font-size: 16px; margin: 22px 0 8px; color: var(--accent); }\n"
    "  .purpose { color: var(--muted); margin: 2px 0 14px; white-space: pre-wrap; }\n"
    "  p { max-width: 74ch; }\n"
    "  .types { background: var(--code-bg); border: 1px solid var(--line); border-radius: 10px;\n"
    "    padding: 12px 16px; margin: 12px 0; overflow-x: auto; }\n"
    "  .types pre { margin: 0; font-size: 13px; white-space: pre; }\n"
    "  table.api { width: 100%; border-collapse: collapse; margin: 10px 0 6px; font-size: 14px; }\n"
    "  table.api td { vertical-align: top; padding: 7px 10px; border-top: 1px solid var(--line); }\n"
    "  table.api td.s { width: 47%; }\n"
    "  table.api .sig { display: inline-block; background: var(--sig-bg); border: 1px solid var(--sig-border);\n"
    "    border-radius: 6px; padding: 2px 7px; font-size: 12.5px; white-space: pre-wrap; line-height: 1.5; }\n"
    "  table.api td.d { color: var(--fg); white-space: pre-wrap; }\n"
    "  table.api td.grp { background: var(--accent-soft); font-size: 11px; font-weight: 700;\n"
    "    text-transform: uppercase; letter-spacing: .06em; color: var(--accent); }\n"
    "  .note { background: var(--accent-soft); border-radius: 8px; padding: 10px 14px; margin: 14px 0;\n"
    "    font-size: 13.5px; }\n"
    "  table.modmap { width: 100%; border-collapse: collapse; margin: 8px 0 6px; font-size: 14px; }\n"
    "  table.modmap td { padding: 5px 10px; border-top: 1px solid var(--line); vertical-align: baseline; }\n"
    "  table.modmap td.m { width: 120px; white-space: nowrap; }\n"
    "  table.modmap td.m a { font-weight: 600; font-family: monospace; }\n"
    "  table.modmap td.grp { background: var(--accent-soft); font-size: 11px; font-weight: 700;\n"
    "    text-transform: uppercase; letter-spacing: .06em; color: var(--accent); padding: 5px 10px;\n"
    "    border-top: 1px solid var(--line); }\n"
    "  footer { color: var(--muted); font-size: 12.5px; margin-top: 60px; border-top: 1px solid var(--line);\n"
    "    padding-top: 16px; }\n"
    "  @media (max-width: 820px) {\n"
    "    nav { display: none; } main { padding: 20px; }\n"
    "  }\n";

const char *const ls_doc_default_template =
    "<!DOCTYPE html>\n<html lang=\"en\"><head><meta charset=\"UTF-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "<title>{{TITLE}}</title>\n<style>\n{{STYLE}}</style></head><body>\n"
    "<div class=\"wrap\">\n<nav>\n<div class=\"brand\">{{TITLE}}<small>generated by ls doc</small></div>\n{{NAV}}</nav>\n"
    "<main>\n<h1>{{TITLE}}</h1>\n{{OVERVIEW}}\n{{CONTENT}}</main>\n</div>\n</body></html>\n";
